openapi: 3.0.0
info:
  title: Title
  description: Introduire les paramètres et les schémas JSON
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /users:
    get:
      summary: Retourne tous les utilisateurs
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Liste de tous les utilisateurs trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "400":
          description: Mauvais type de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"



components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Bob"
        email:
          type: string
          example: "bob@mail.com"
